AllCops:
  TargetRubyVersion: 2.2

Documentation:
  Enabled: false

AccessorMethodName:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

BlockLength:
  Exclude:
    - './spec/*_spec.rb'
    - 'site_prism.gemspec'

# Offense count: 7
Metrics/LineLength:
  Max: 90

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true
